// Generated by Scripts/generate-ai-agent-catalog.py. Do not edit by hand.
//
// Source: https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json
// Upstream is MIT licensed. Agents: 175.
//
// Columns, tab separated: user-agent token, purpose, operator, respects robots.txt.
// Purpose is OUR classification, not upstream's: see the script for how each row
// was decided and which agents are hand-audited.

enum AIAgentCatalogData {
    /// One agent per line. Parsed once, lazily, by `AIAgentCatalog`.
    static let tsv = """
AddSearchBot	aiSearch	Unknown	unknown
AgentTimes	scraper	The Agent Times	unknown
AI2Bot	training	Ai2	yes
AI2Bot-DeepResearchEval	userTriggered	Ai2, a non-profit AI research institute	unknown
Ai2Bot-Dolma	training	Ai2	yes
aiHitBot	training	aiHit	yes
AIWebIndex	aiSearch	Lyrenth	yes
amazon-kendra	aiSearch	Amazon	yes
amazon-QBusiness	userTriggered	Unknown	unknown
Amazonbot	aiSearch	Amazon	yes
AmazonBuyForMe	agent	Amazon	unknown
Amzn-SearchBot	aiSearch	Unknown	unknown
Amzn-User	userTriggered	Amazon, used for fetching web content to answer user queries through Alexa and other Amazon AI services	unknown
Andibot	userTriggered	Andi	unknown
Anomura	aiSearch	Direqt	yes
anthropic-ai	training	Anthropic	unknown
ApifyBot	scraper	Unknown	unknown
ApifyWebsiteContentCrawler	scraper	Unknown	unknown
Applebot	aiSearch	Unknown	yes
Applebot-Extended	training	Apple	yes
Aranet-SearchBot	agent	Unknown	unknown
atlassian-bot	userTriggered	Atlassian	yes
Awario	scraper	Awario	unknown
AzureAI-SearchBot	aiSearch	Unknown	unknown
bedrockbot	scraper	Amazon	yes
bigsur.ai	userTriggered	Big Sur AI that fetches website content to enable AI-powered web agents, sales assistants, and content marketing solutions for busi…	unknown
Bravebot	scraper	https://safe.search.brave.com/help/brave-search-crawler	yes
Brightbot	scraper	Unknown	unknown
Brightbot 1.0	training	https://brightdata.com/brightbot	unknown
BuddyBot	scraper	BuddyBotLearning	unknown
Bytespider	training	ByteDance	no
CCBot	training	Common Crawl Foundation	yes
Channel3Bot	aiSearch	Unknown	unknown
ChatGLM-Spider	scraper	Unknown	unknown
ChatGPT Agent	agent	OpenAI	yes
ChatGPT-User	userTriggered	OpenAI	yes
Claude-Code	agent	Unknown	unknown
Claude-SearchBot	aiSearch	Anthropic	yes
Claude-User	userTriggered	Anthropic	yes
Claude-Web	agent	Anthropic	unknown
ClaudeBot	training	Anthropic	yes
Cloudflare-AutoRAG	aiSearch	Cloudflare	yes
CloudVertexBot	scraper	Unknown	unknown
Code	agent	Unknown	unknown
cohere-ai	userTriggered	Cohere	unknown
cohere-training-data-crawler	scraper	Cohere to download training data for its LLMs (Large Language Models) that power its enterprise AI products	unknown
Cotoyogi	training	ROIS	yes
CragCrawler	scraper	CragSoftware, a Brazil-based software company specializing in data engineering and AI web scraping services	unknown
Crawl4AI	agent	Unknown	unknown
Crawlspace	scraper	Crawlspace	yes
Cursor	agent	Unknown	unknown
Datenbank Crawler	scraper	Datenbank	unknown
DeepSeekBot	training	DeepSeek	no
Devin	agent	Devin AI	yes
Diffbot	training	Diffbot	unknown
Diffbot-User	userTriggered	Diffbot	yes
DoubaoBot	userTriggered	ByteDance	unknown
DuckAssistBot	userTriggered	Unknown	yes
Echobot Bot	scraper	Echobox	unknown
EchoboxBot	scraper	Echobox	unknown
ERNIEBot	scraper	Baidu	unknown
ExaBot	scraper	Unknown	unknown
ExaSearchBot	aiSearch	Exa	unknown
FacebookBot	training	Meta/Facebook	yes
facebookexternalhit	scraper	Meta/Facebook	no
Factset_spyderbot	training	Factset	unknown
FirecrawlAgent	scraper	Firecrawl that extracts web content and converts it into structured data for use in LLM and AI applications	yes
FriendlyCrawler	training	Unknown	yes
GeistHaus-PageFetcher	userTriggered	GeistHaus, a company developing AI systems for therapy and psychological assessment	unknown
Gemini-Deep-Research	userTriggered	Unknown	unknown
Google-Agent	agent	Unknown	yes
Google-CloudVertexBot	training	Google	yes
Google-Extended	training	Google	yes
Google-Firebase	scraper	Google	unknown
Google-Gemini-CLI	agent	Unknown	unknown
Google-NotebookLM	userTriggered	Unknown	unknown
GoogleAgent-Mariner	agent	Google	unknown
GoogleAgent-URLContext	userTriggered	Google that retrieves web content on behalf of Gemini API users	unknown
GoogleOther	aiSearch	Google	yes
GoogleOther-Image	aiSearch	Google	yes
GoogleOther-Video	aiSearch	Google	yes
GPTBot	training	OpenAI	yes
HenkBot	scraper	Unknown	unknown
iAskBot	agent	Unknown	unknown
iaskspider	agent	Unknown	unknown
iaskspider/2.0	userTriggered	iAsk	no
ICC-Crawler	training	NICT	yes
ImagesiftBot	aiSearch	ImageSift	yes
imageSpider	scraper	Unknown	unknown
img2dataset	training	img2dataset	unknown
ISSCyberRiskCrawler	training	ISS-Corporate	no
kagi-fetcher	userTriggered	Kagi that fetches web content to answer user queries through Kagi AI, their suite of AI-powered tools including Assistant, Res…	unknown
Kangaroo Bot	training	Unknown	unknown
Kimi-SearchBot	aiSearch	Moonshot AI	yes
Kimi-User	userTriggered	Moonshot AI that fetches web content on behalf of users interacting with Kimi	unknown
KimiBot	scraper	Moonshot AI	yes
KlaviyoAIBot	userTriggered	Klaviyo	yes
KunatoCrawler	agent	Unknown	unknown
laion-huggingface-processor	scraper	Unknown	unknown
LAIONDownloader	aiSearch	Large-scale Artificial Intelligence Open Network	no
LCC	scraper	Unknown	unknown
Lightpanda	scraper	Anyone who downloads the Lightpanda client. Possibly being used by a Grok-adjacent organization's botnet.	unknown
LinerBot	userTriggered	Unknown	unknown
Linguee Bot	training	Linguee	no
LinkupBot	aiSearch	Unknown	unknown
Manus-User	agent	Butterfly Effect, a company based in China	unknown
meta-externalagent	training	Meta	yes
Meta-ExternalAgent	scraper	Unknown	yes
meta-externalfetcher	userTriggered	Unknown	no
Meta-ExternalFetcher	userTriggered	Unknown	no
meta-webindexer	userTriggered	Meta	unknown
MistralAI-Index	aiSearch	Mistral AI	yes
MistralAI-Training	scraper	Mistral AI	yes
MistralAI-User	aiSearch	Mistral	unknown
MistralAI-User/1.0	userTriggered	Mistral AI	yes
Mozilla-Tabstack	scraper	Mozilla that performs programmatic, AI-driven interactions with web content through Tabstack	yes
MyCentralAIScraperBot	scraper	Unknown	unknown
NagetBot	scraper	Naget Inc (founded by Chris Samarinas, headquarter in Amherst, Massachusetts)	unknown
netEstate Imprint Crawler	scraper	netEstate	unknown
newsai	scraper	Unknown	unknown
NotebookLM	userTriggered	Unknown	unknown
NovaAct	agent	Unknown	unknown
OAI-AdsBot	training	OpenAI	unknown
OAI-SearchBot	aiSearch	OpenAI	yes
omgili	training	Webz.io	yes
omgilibot	aiSearch	Webz.io	yes
OpenAI	scraper	OpenAI	yes
opencode	agent	Unknown	unknown
Operator	agent	Unknown	unknown
PanguBot	training	the Chinese company Huawei	unknown
Panscient	training	Panscient	yes
panscient.com	training	Panscient	yes
Perplexity-User	userTriggered	Perplexity	no
PerplexityBot	aiSearch	Perplexity	yes
PetalBot	userTriggered	Huawei	yes
PhindBot	userTriggered	phind	unknown
Poggio-Citations	userTriggered	Poggio, a company that provides AI sales enablement tools for creating tailored narratives, business cases, and account plan…	unknown
Poseidon Research Crawler	aiSearch	Poseidon Research	unknown
QualifiedBot	userTriggered	Qualified	unknown
Querit-SearchBot	scraper	Querit that indexes web content for their search API service, which is designed to provide real-time search results for larg…	unknown
QueritBot	scraper	Querit, a company providing a search API for large language model integration	unknown
QuillBot	scraper	Quillbot	unknown
quillbot.com	scraper	Quillbot	unknown
QwenBot	scraper	Alibaba	unknown
Reflectionbot	agent	Reflection	unknown
SBIntuitionsBot	scraper	SB Intuitions	yes
Scrapy	training	Zyte	unknown
SemrushBot-OCOB	scraper	Semrush	yes
SemrushBot-SWA	userTriggered	Semrush	yes
Shap-User	userTriggered	Unknown	unknown
ShapBot	scraper	Parallel	yes
Sidetrade indexer bot	training	Sidetrade	unknown
Spider	scraper	Unknown	unknown
TavilyBot	scraper	Unknown	unknown
Terra Cotta	scraper	Unknown	unknown
TerraCotta	scraper	Ceramic AI	yes
Thinkbot	scraper	Thinkbot	no
TikTokSpider	training	ByteDance	unknown
Timpibot	training	Timpi	unknown
TongyiBot	userTriggered	Alibaba that fetches web content for the Tongyi Qianwen assistant and related Qwen-generated answers	unknown
Trae	agent	Unknown	unknown
TwinAgent	agent	Twin, a platform that creates automated workers to perform tasks by integrating with APIs and controlling web applications through browser automa…	unknown
UseAI	userTriggered	Unknown	unknown
VelenPublicWebCrawler	training	Velen Crawler	yes
WARDBot	scraper	WEBSPARK	unknown
Webzio-Extended	scraper	Unknown	unknown
webzio-extended	scraper	Unknown	unknown
wpbot	scraper	QuantumCloud	unknown
WRTNBot	agent	Unknown	unknown
YaK	aiSearch	Meltwater	unknown
YandexAdditional	training	Yandex	yes
YandexAdditionalBot	scraper	Yandex	yes
YiyanBot	userTriggered	Baidu that fetches web content for the yiyan	unknown
YouBot	aiSearch	You	yes
ZanistaBot	aiSearch	Unknown	unknown
"""
}
