// Regenerates Sources/SwiftlyBotKit/Configuration/BotKitTimeZone.swift, one
// enum case per IANA time zone Foundation knows about.
//
// Usage, from the package root:
//
//     swift Scripts/generate-time-zones.swift
//
// Run it on macOS: its tz database is the complete, current one, and every name
// it lists is also known to PostgreSQL, which is handed the same identifier.
// Rerun it when a tzdata release adds a zone; existing case names never change
// because they are derived from the identifier alone.

import Foundation

/// `America/Port-au-Prince` becomes `americaPortAuPrince`.
func caseName(for identifier: String) -> String {
    let words = identifier
        .split(whereSeparator: { "/_-".contains($0) })
        .map(String.init)
    return words.enumerated().map { index, word in
        index == 0
            ? word.prefix(1).lowercased() + word.dropFirst()
            : word.prefix(1).uppercased() + word.dropFirst()
    }.joined()
}

// `GMT` is left out: `.utc` covers it, and one name per offset-free zone is enough.
let identifiers = TimeZone.knownTimeZoneIdentifiers
    .filter { $0.contains("/") }
    .sorted()

var seen: [String: String] = [:]
for identifier in identifiers {
    let name = caseName(for: identifier)
    if let clash = seen[name] {
        fatalError("\(identifier) and \(clash) both map to .\(name)")
    }
    seen[name] = identifier
}

let grouped = Dictionary(grouping: identifiers) { String($0.split(separator: "/")[0]) }

var out = """
// GENERATED by Scripts/generate-time-zones.swift. Do not hand-edit.
// \(identifiers.count) zones, plus `.utc` and `.custom`.

import Foundation

/// The time zone the dashboard draws its hourly and daily buckets in.
///
/// One case per IANA time zone, named after its identifier, so the zone is
/// picked from autocomplete instead of typed as a string:
///
/// ```swift
/// config.dashboard.timeZone = .americaNewYork
/// config.dashboard.timeZone = .europeBrussels
/// config.dashboard.timeZone = .asiaTokyo
/// ```
///
/// Every case maps to a real IANA identifier, which is what PostgreSQL is
/// handed on the SQL side of the query. Use ``custom(_:)`` only for a zone this
/// list does not have yet, and give it an IANA identifier too: a fixed-offset
/// `TimeZone(secondsFromGMT:)` reports itself as `GMT+0100`, which PostgreSQL
/// reads with the opposite (POSIX) sign.
public enum BotKitTimeZone: Hashable, Sendable {

    /// Coordinated Universal Time. The package default.
    case utc

    /// Any Foundation time zone. Prefer a named case; see the type's
    /// discussion for why a fixed-offset zone gives wrong buckets.
    case custom(TimeZone)

"""

for region in grouped.keys.sorted() {
    out += "    // MARK: \(region)\n\n"
    for identifier in grouped[region]! {
        out += "    /// `\(identifier)`\n"
        out += "    case \(caseName(for: identifier))\n"
    }
    out += "\n"
}

out += """
    /// Every named case, `.utc` first, then alphabetically by identifier.
    /// ``custom(_:)`` is not included.
    public static let allNamed: [BotKitTimeZone] = [
        .utc,

"""
for identifier in identifiers {
    out += "        .\(caseName(for: identifier)),\n"
}
out += """
    ]

    /// The IANA identifier, for example `America/New_York`.
    public var identifier: String {
        switch self {
        case .utc: return "UTC"
        case .custom(let timeZone): return timeZone.identifier

"""
for identifier in identifiers {
    out += "        case .\(caseName(for: identifier)): return \"\(identifier)\"\n"
}
out += """
        }
    }
}

"""

let scriptURL = URL(fileURLWithPath: CommandLine.arguments[0]).standardizedFileURL
let packageRoot = scriptURL.deletingLastPathComponent().deletingLastPathComponent()
let target = packageRoot
    .appendingPathComponent("Sources/SwiftlyBotKit/Configuration/BotKitTimeZone.swift")
try out.write(to: target, atomically: true, encoding: .utf8)
print("Wrote \(identifiers.count) zones to \(target.path)")
