// GENERATED by Scripts/generate-time-zones.swift from tzdata 2026c-rearguard. Do not hand-edit.
// 418 canonical zones, plus `.utc` and `.custom`; 25 deprecated aliases.

import Foundation

/// The time zone the dashboard draws its hourly and daily buckets in.
///
/// One case per canonical IANA time zone (the `zone.tab` list), named after
/// its identifier, so the zone is picked from autocomplete instead of typed as
/// a string:
///
/// ```swift
/// config.dashboard.timeZone = .americaNewYork
/// config.dashboard.timeZone = .europeBrussels
/// config.dashboard.timeZone = .asiaTokyo
/// ```
///
/// Legacy spellings such as `.asiaCalcutta` or `.europeKiev` remain as
/// deprecated aliases of the canonical case (`.asiaKolkata`, `.europeKyiv`),
/// and ``init(identifier:)`` maps any legacy name to its canonical case.
///
/// All bucket arithmetic happens in Swift, with Foundation's rules for the
/// zone; PostgreSQL is never handed the zone name. So ``custom(_:)`` also
/// accepts a fixed-offset zone such as `TimeZone(secondsFromGMT: 3600)`: it
/// buckets correctly, it just never observes daylight saving time.
///
/// A zone newer than the host's tz database (for example `America/Coyhaique`
/// on an older Linux image) cannot be resolved by Foundation. Its
/// ``foundationTimeZone`` is then UTC, and ``isAvailable`` is `false`.
public enum BotKitTimeZone: Hashable, Sendable {

    /// Coordinated Universal Time. The package default.
    case utc

    /// Any Foundation time zone: a zone this list does not have yet, or a
    /// fixed offset such as `TimeZone(secondsFromGMT: 3600)`. Prefer a named
    /// case for a real place, so daylight saving time is followed.
    case custom(TimeZone)
    // MARK: Africa

    /// `Africa/Abidjan`
    case africaAbidjan
    /// `Africa/Accra`
    case africaAccra
    /// `Africa/Addis_Ababa`
    case africaAddisAbaba
    /// `Africa/Algiers`
    case africaAlgiers
    /// `Africa/Asmara`
    case africaAsmara
    /// `Africa/Bamako`
    case africaBamako
    /// `Africa/Bangui`
    case africaBangui
    /// `Africa/Banjul`
    case africaBanjul
    /// `Africa/Bissau`
    case africaBissau
    /// `Africa/Blantyre`
    case africaBlantyre
    /// `Africa/Brazzaville`
    case africaBrazzaville
    /// `Africa/Bujumbura`
    case africaBujumbura
    /// `Africa/Cairo`
    case africaCairo
    /// `Africa/Casablanca`
    case africaCasablanca
    /// `Africa/Ceuta`
    case africaCeuta
    /// `Africa/Conakry`
    case africaConakry
    /// `Africa/Dakar`
    case africaDakar
    /// `Africa/Dar_es_Salaam`
    case africaDarEsSalaam
    /// `Africa/Djibouti`
    case africaDjibouti
    /// `Africa/Douala`
    case africaDouala
    /// `Africa/El_Aaiun`
    case africaElAaiun
    /// `Africa/Freetown`
    case africaFreetown
    /// `Africa/Gaborone`
    case africaGaborone
    /// `Africa/Harare`
    case africaHarare
    /// `Africa/Johannesburg`
    case africaJohannesburg
    /// `Africa/Juba`
    case africaJuba
    /// `Africa/Kampala`
    case africaKampala
    /// `Africa/Khartoum`
    case africaKhartoum
    /// `Africa/Kigali`
    case africaKigali
    /// `Africa/Kinshasa`
    case africaKinshasa
    /// `Africa/Lagos`
    case africaLagos
    /// `Africa/Libreville`
    case africaLibreville
    /// `Africa/Lome`
    case africaLome
    /// `Africa/Luanda`
    case africaLuanda
    /// `Africa/Lubumbashi`
    case africaLubumbashi
    /// `Africa/Lusaka`
    case africaLusaka
    /// `Africa/Malabo`
    case africaMalabo
    /// `Africa/Maputo`
    case africaMaputo
    /// `Africa/Maseru`
    case africaMaseru
    /// `Africa/Mbabane`
    case africaMbabane
    /// `Africa/Mogadishu`
    case africaMogadishu
    /// `Africa/Monrovia`
    case africaMonrovia
    /// `Africa/Nairobi`
    case africaNairobi
    /// `Africa/Ndjamena`
    case africaNdjamena
    /// `Africa/Niamey`
    case africaNiamey
    /// `Africa/Nouakchott`
    case africaNouakchott
    /// `Africa/Ouagadougou`
    case africaOuagadougou
    /// `Africa/Porto-Novo`
    case africaPortoNovo
    /// `Africa/Sao_Tome`
    case africaSaoTome
    /// `Africa/Tripoli`
    case africaTripoli
    /// `Africa/Tunis`
    case africaTunis
    /// `Africa/Windhoek`
    case africaWindhoek

    // MARK: America

    /// `America/Adak`
    case americaAdak
    /// `America/Anchorage`
    case americaAnchorage
    /// `America/Anguilla`
    case americaAnguilla
    /// `America/Antigua`
    case americaAntigua
    /// `America/Araguaina`
    case americaAraguaina
    /// `America/Argentina/Buenos_Aires`
    case americaArgentinaBuenosAires
    /// `America/Argentina/Catamarca`
    case americaArgentinaCatamarca
    /// `America/Argentina/Cordoba`
    case americaArgentinaCordoba
    /// `America/Argentina/Jujuy`
    case americaArgentinaJujuy
    /// `America/Argentina/La_Rioja`
    case americaArgentinaLaRioja
    /// `America/Argentina/Mendoza`
    case americaArgentinaMendoza
    /// `America/Argentina/Rio_Gallegos`
    case americaArgentinaRioGallegos
    /// `America/Argentina/Salta`
    case americaArgentinaSalta
    /// `America/Argentina/San_Juan`
    case americaArgentinaSanJuan
    /// `America/Argentina/San_Luis`
    case americaArgentinaSanLuis
    /// `America/Argentina/Tucuman`
    case americaArgentinaTucuman
    /// `America/Argentina/Ushuaia`
    case americaArgentinaUshuaia
    /// `America/Aruba`
    case americaAruba
    /// `America/Asuncion`
    case americaAsuncion
    /// `America/Atikokan`
    case americaAtikokan
    /// `America/Bahia`
    case americaBahia
    /// `America/Bahia_Banderas`
    case americaBahiaBanderas
    /// `America/Barbados`
    case americaBarbados
    /// `America/Belem`
    case americaBelem
    /// `America/Belize`
    case americaBelize
    /// `America/Blanc-Sablon`
    case americaBlancSablon
    /// `America/Boa_Vista`
    case americaBoaVista
    /// `America/Bogota`
    case americaBogota
    /// `America/Boise`
    case americaBoise
    /// `America/Cambridge_Bay`
    case americaCambridgeBay
    /// `America/Campo_Grande`
    case americaCampoGrande
    /// `America/Cancun`
    case americaCancun
    /// `America/Caracas`
    case americaCaracas
    /// `America/Cayenne`
    case americaCayenne
    /// `America/Cayman`
    case americaCayman
    /// `America/Chicago`
    case americaChicago
    /// `America/Chihuahua`
    case americaChihuahua
    /// `America/Ciudad_Juarez`
    case americaCiudadJuarez
    /// `America/Costa_Rica`
    case americaCostaRica
    /// `America/Coyhaique`
    case americaCoyhaique
    /// `America/Creston`
    case americaCreston
    /// `America/Cuiaba`
    case americaCuiaba
    /// `America/Curacao`
    case americaCuracao
    /// `America/Danmarkshavn`
    case americaDanmarkshavn
    /// `America/Dawson`
    case americaDawson
    /// `America/Dawson_Creek`
    case americaDawsonCreek
    /// `America/Denver`
    case americaDenver
    /// `America/Detroit`
    case americaDetroit
    /// `America/Dominica`
    case americaDominica
    /// `America/Edmonton`
    case americaEdmonton
    /// `America/Eirunepe`
    case americaEirunepe
    /// `America/El_Salvador`
    case americaElSalvador
    /// `America/Fort_Nelson`
    case americaFortNelson
    /// `America/Fortaleza`
    case americaFortaleza
    /// `America/Glace_Bay`
    case americaGlaceBay
    /// `America/Goose_Bay`
    case americaGooseBay
    /// `America/Grand_Turk`
    case americaGrandTurk
    /// `America/Grenada`
    case americaGrenada
    /// `America/Guadeloupe`
    case americaGuadeloupe
    /// `America/Guatemala`
    case americaGuatemala
    /// `America/Guayaquil`
    case americaGuayaquil
    /// `America/Guyana`
    case americaGuyana
    /// `America/Halifax`
    case americaHalifax
    /// `America/Havana`
    case americaHavana
    /// `America/Hermosillo`
    case americaHermosillo
    /// `America/Indiana/Indianapolis`
    case americaIndianaIndianapolis
    /// `America/Indiana/Knox`
    case americaIndianaKnox
    /// `America/Indiana/Marengo`
    case americaIndianaMarengo
    /// `America/Indiana/Petersburg`
    case americaIndianaPetersburg
    /// `America/Indiana/Tell_City`
    case americaIndianaTellCity
    /// `America/Indiana/Vevay`
    case americaIndianaVevay
    /// `America/Indiana/Vincennes`
    case americaIndianaVincennes
    /// `America/Indiana/Winamac`
    case americaIndianaWinamac
    /// `America/Inuvik`
    case americaInuvik
    /// `America/Iqaluit`
    case americaIqaluit
    /// `America/Jamaica`
    case americaJamaica
    /// `America/Juneau`
    case americaJuneau
    /// `America/Kentucky/Louisville`
    case americaKentuckyLouisville
    /// `America/Kentucky/Monticello`
    case americaKentuckyMonticello
    /// `America/Kralendijk`
    case americaKralendijk
    /// `America/La_Paz`
    case americaLaPaz
    /// `America/Lima`
    case americaLima
    /// `America/Los_Angeles`
    case americaLosAngeles
    /// `America/Lower_Princes`
    case americaLowerPrinces
    /// `America/Maceio`
    case americaMaceio
    /// `America/Managua`
    case americaManagua
    /// `America/Manaus`
    case americaManaus
    /// `America/Marigot`
    case americaMarigot
    /// `America/Martinique`
    case americaMartinique
    /// `America/Matamoros`
    case americaMatamoros
    /// `America/Mazatlan`
    case americaMazatlan
    /// `America/Menominee`
    case americaMenominee
    /// `America/Merida`
    case americaMerida
    /// `America/Metlakatla`
    case americaMetlakatla
    /// `America/Mexico_City`
    case americaMexicoCity
    /// `America/Miquelon`
    case americaMiquelon
    /// `America/Moncton`
    case americaMoncton
    /// `America/Monterrey`
    case americaMonterrey
    /// `America/Montevideo`
    case americaMontevideo
    /// `America/Montserrat`
    case americaMontserrat
    /// `America/Nassau`
    case americaNassau
    /// `America/New_York`
    case americaNewYork
    /// `America/Nome`
    case americaNome
    /// `America/Noronha`
    case americaNoronha
    /// `America/North_Dakota/Beulah`
    case americaNorthDakotaBeulah
    /// `America/North_Dakota/Center`
    case americaNorthDakotaCenter
    /// `America/North_Dakota/New_Salem`
    case americaNorthDakotaNewSalem
    /// `America/Nuuk`
    case americaNuuk
    /// `America/Ojinaga`
    case americaOjinaga
    /// `America/Panama`
    case americaPanama
    /// `America/Paramaribo`
    case americaParamaribo
    /// `America/Phoenix`
    case americaPhoenix
    /// `America/Port-au-Prince`
    case americaPortAuPrince
    /// `America/Port_of_Spain`
    case americaPortOfSpain
    /// `America/Porto_Velho`
    case americaPortoVelho
    /// `America/Puerto_Rico`
    case americaPuertoRico
    /// `America/Punta_Arenas`
    case americaPuntaArenas
    /// `America/Rankin_Inlet`
    case americaRankinInlet
    /// `America/Recife`
    case americaRecife
    /// `America/Regina`
    case americaRegina
    /// `America/Resolute`
    case americaResolute
    /// `America/Rio_Branco`
    case americaRioBranco
    /// `America/Santarem`
    case americaSantarem
    /// `America/Santiago`
    case americaSantiago
    /// `America/Santo_Domingo`
    case americaSantoDomingo
    /// `America/Sao_Paulo`
    case americaSaoPaulo
    /// `America/Scoresbysund`
    case americaScoresbysund
    /// `America/Sitka`
    case americaSitka
    /// `America/St_Barthelemy`
    case americaStBarthelemy
    /// `America/St_Johns`
    case americaStJohns
    /// `America/St_Kitts`
    case americaStKitts
    /// `America/St_Lucia`
    case americaStLucia
    /// `America/St_Thomas`
    case americaStThomas
    /// `America/St_Vincent`
    case americaStVincent
    /// `America/Swift_Current`
    case americaSwiftCurrent
    /// `America/Tegucigalpa`
    case americaTegucigalpa
    /// `America/Thule`
    case americaThule
    /// `America/Tijuana`
    case americaTijuana
    /// `America/Toronto`
    case americaToronto
    /// `America/Tortola`
    case americaTortola
    /// `America/Vancouver`
    case americaVancouver
    /// `America/Whitehorse`
    case americaWhitehorse
    /// `America/Winnipeg`
    case americaWinnipeg
    /// `America/Yakutat`
    case americaYakutat

    // MARK: Antarctica

    /// `Antarctica/Casey`
    case antarcticaCasey
    /// `Antarctica/Davis`
    case antarcticaDavis
    /// `Antarctica/DumontDUrville`
    case antarcticaDumontDUrville
    /// `Antarctica/Macquarie`
    case antarcticaMacquarie
    /// `Antarctica/Mawson`
    case antarcticaMawson
    /// `Antarctica/McMurdo`
    case antarcticaMcMurdo
    /// `Antarctica/Palmer`
    case antarcticaPalmer
    /// `Antarctica/Rothera`
    case antarcticaRothera
    /// `Antarctica/Syowa`
    case antarcticaSyowa
    /// `Antarctica/Troll`
    case antarcticaTroll
    /// `Antarctica/Vostok`
    case antarcticaVostok

    // MARK: Arctic

    /// `Arctic/Longyearbyen`
    case arcticLongyearbyen

    // MARK: Asia

    /// `Asia/Aden`
    case asiaAden
    /// `Asia/Almaty`
    case asiaAlmaty
    /// `Asia/Amman`
    case asiaAmman
    /// `Asia/Anadyr`
    case asiaAnadyr
    /// `Asia/Aqtau`
    case asiaAqtau
    /// `Asia/Aqtobe`
    case asiaAqtobe
    /// `Asia/Ashgabat`
    case asiaAshgabat
    /// `Asia/Atyrau`
    case asiaAtyrau
    /// `Asia/Baghdad`
    case asiaBaghdad
    /// `Asia/Bahrain`
    case asiaBahrain
    /// `Asia/Baku`
    case asiaBaku
    /// `Asia/Bangkok`
    case asiaBangkok
    /// `Asia/Barnaul`
    case asiaBarnaul
    /// `Asia/Beirut`
    case asiaBeirut
    /// `Asia/Bishkek`
    case asiaBishkek
    /// `Asia/Brunei`
    case asiaBrunei
    /// `Asia/Chita`
    case asiaChita
    /// `Asia/Colombo`
    case asiaColombo
    /// `Asia/Damascus`
    case asiaDamascus
    /// `Asia/Dhaka`
    case asiaDhaka
    /// `Asia/Dili`
    case asiaDili
    /// `Asia/Dubai`
    case asiaDubai
    /// `Asia/Dushanbe`
    case asiaDushanbe
    /// `Asia/Famagusta`
    case asiaFamagusta
    /// `Asia/Gaza`
    case asiaGaza
    /// `Asia/Hebron`
    case asiaHebron
    /// `Asia/Ho_Chi_Minh`
    case asiaHoChiMinh
    /// `Asia/Hong_Kong`
    case asiaHongKong
    /// `Asia/Hovd`
    case asiaHovd
    /// `Asia/Irkutsk`
    case asiaIrkutsk
    /// `Asia/Jakarta`
    case asiaJakarta
    /// `Asia/Jayapura`
    case asiaJayapura
    /// `Asia/Jerusalem`
    case asiaJerusalem
    /// `Asia/Kabul`
    case asiaKabul
    /// `Asia/Kamchatka`
    case asiaKamchatka
    /// `Asia/Karachi`
    case asiaKarachi
    /// `Asia/Kathmandu`
    case asiaKathmandu
    /// `Asia/Khandyga`
    case asiaKhandyga
    /// `Asia/Kolkata`
    case asiaKolkata
    /// `Asia/Krasnoyarsk`
    case asiaKrasnoyarsk
    /// `Asia/Kuala_Lumpur`
    case asiaKualaLumpur
    /// `Asia/Kuching`
    case asiaKuching
    /// `Asia/Kuwait`
    case asiaKuwait
    /// `Asia/Macau`
    case asiaMacau
    /// `Asia/Magadan`
    case asiaMagadan
    /// `Asia/Makassar`
    case asiaMakassar
    /// `Asia/Manila`
    case asiaManila
    /// `Asia/Muscat`
    case asiaMuscat
    /// `Asia/Nicosia`
    case asiaNicosia
    /// `Asia/Novokuznetsk`
    case asiaNovokuznetsk
    /// `Asia/Novosibirsk`
    case asiaNovosibirsk
    /// `Asia/Omsk`
    case asiaOmsk
    /// `Asia/Oral`
    case asiaOral
    /// `Asia/Phnom_Penh`
    case asiaPhnomPenh
    /// `Asia/Pontianak`
    case asiaPontianak
    /// `Asia/Pyongyang`
    case asiaPyongyang
    /// `Asia/Qatar`
    case asiaQatar
    /// `Asia/Qostanay`
    case asiaQostanay
    /// `Asia/Qyzylorda`
    case asiaQyzylorda
    /// `Asia/Riyadh`
    case asiaRiyadh
    /// `Asia/Sakhalin`
    case asiaSakhalin
    /// `Asia/Samarkand`
    case asiaSamarkand
    /// `Asia/Seoul`
    case asiaSeoul
    /// `Asia/Shanghai`
    case asiaShanghai
    /// `Asia/Singapore`
    case asiaSingapore
    /// `Asia/Srednekolymsk`
    case asiaSrednekolymsk
    /// `Asia/Taipei`
    case asiaTaipei
    /// `Asia/Tashkent`
    case asiaTashkent
    /// `Asia/Tbilisi`
    case asiaTbilisi
    /// `Asia/Tehran`
    case asiaTehran
    /// `Asia/Thimphu`
    case asiaThimphu
    /// `Asia/Tokyo`
    case asiaTokyo
    /// `Asia/Tomsk`
    case asiaTomsk
    /// `Asia/Ulaanbaatar`
    case asiaUlaanbaatar
    /// `Asia/Urumqi`
    case asiaUrumqi
    /// `Asia/Ust-Nera`
    case asiaUstNera
    /// `Asia/Vientiane`
    case asiaVientiane
    /// `Asia/Vladivostok`
    case asiaVladivostok
    /// `Asia/Yakutsk`
    case asiaYakutsk
    /// `Asia/Yangon`
    case asiaYangon
    /// `Asia/Yekaterinburg`
    case asiaYekaterinburg
    /// `Asia/Yerevan`
    case asiaYerevan

    // MARK: Atlantic

    /// `Atlantic/Azores`
    case atlanticAzores
    /// `Atlantic/Bermuda`
    case atlanticBermuda
    /// `Atlantic/Canary`
    case atlanticCanary
    /// `Atlantic/Cape_Verde`
    case atlanticCapeVerde
    /// `Atlantic/Faroe`
    case atlanticFaroe
    /// `Atlantic/Madeira`
    case atlanticMadeira
    /// `Atlantic/Reykjavik`
    case atlanticReykjavik
    /// `Atlantic/South_Georgia`
    case atlanticSouthGeorgia
    /// `Atlantic/St_Helena`
    case atlanticStHelena
    /// `Atlantic/Stanley`
    case atlanticStanley

    // MARK: Australia

    /// `Australia/Adelaide`
    case australiaAdelaide
    /// `Australia/Brisbane`
    case australiaBrisbane
    /// `Australia/Broken_Hill`
    case australiaBrokenHill
    /// `Australia/Darwin`
    case australiaDarwin
    /// `Australia/Eucla`
    case australiaEucla
    /// `Australia/Hobart`
    case australiaHobart
    /// `Australia/Lindeman`
    case australiaLindeman
    /// `Australia/Lord_Howe`
    case australiaLordHowe
    /// `Australia/Melbourne`
    case australiaMelbourne
    /// `Australia/Perth`
    case australiaPerth
    /// `Australia/Sydney`
    case australiaSydney

    // MARK: Europe

    /// `Europe/Amsterdam`
    case europeAmsterdam
    /// `Europe/Andorra`
    case europeAndorra
    /// `Europe/Astrakhan`
    case europeAstrakhan
    /// `Europe/Athens`
    case europeAthens
    /// `Europe/Belgrade`
    case europeBelgrade
    /// `Europe/Berlin`
    case europeBerlin
    /// `Europe/Bratislava`
    case europeBratislava
    /// `Europe/Brussels`
    case europeBrussels
    /// `Europe/Bucharest`
    case europeBucharest
    /// `Europe/Budapest`
    case europeBudapest
    /// `Europe/Busingen`
    case europeBusingen
    /// `Europe/Chisinau`
    case europeChisinau
    /// `Europe/Copenhagen`
    case europeCopenhagen
    /// `Europe/Dublin`
    case europeDublin
    /// `Europe/Gibraltar`
    case europeGibraltar
    /// `Europe/Guernsey`
    case europeGuernsey
    /// `Europe/Helsinki`
    case europeHelsinki
    /// `Europe/Isle_of_Man`
    case europeIsleOfMan
    /// `Europe/Istanbul`
    case europeIstanbul
    /// `Europe/Jersey`
    case europeJersey
    /// `Europe/Kaliningrad`
    case europeKaliningrad
    /// `Europe/Kirov`
    case europeKirov
    /// `Europe/Kyiv`
    case europeKyiv
    /// `Europe/Lisbon`
    case europeLisbon
    /// `Europe/Ljubljana`
    case europeLjubljana
    /// `Europe/London`
    case europeLondon
    /// `Europe/Luxembourg`
    case europeLuxembourg
    /// `Europe/Madrid`
    case europeMadrid
    /// `Europe/Malta`
    case europeMalta
    /// `Europe/Mariehamn`
    case europeMariehamn
    /// `Europe/Minsk`
    case europeMinsk
    /// `Europe/Monaco`
    case europeMonaco
    /// `Europe/Moscow`
    case europeMoscow
    /// `Europe/Oslo`
    case europeOslo
    /// `Europe/Paris`
    case europeParis
    /// `Europe/Podgorica`
    case europePodgorica
    /// `Europe/Prague`
    case europePrague
    /// `Europe/Riga`
    case europeRiga
    /// `Europe/Rome`
    case europeRome
    /// `Europe/Samara`
    case europeSamara
    /// `Europe/San_Marino`
    case europeSanMarino
    /// `Europe/Sarajevo`
    case europeSarajevo
    /// `Europe/Saratov`
    case europeSaratov
    /// `Europe/Simferopol`
    case europeSimferopol
    /// `Europe/Skopje`
    case europeSkopje
    /// `Europe/Sofia`
    case europeSofia
    /// `Europe/Stockholm`
    case europeStockholm
    /// `Europe/Tallinn`
    case europeTallinn
    /// `Europe/Tirane`
    case europeTirane
    /// `Europe/Ulyanovsk`
    case europeUlyanovsk
    /// `Europe/Vaduz`
    case europeVaduz
    /// `Europe/Vatican`
    case europeVatican
    /// `Europe/Vienna`
    case europeVienna
    /// `Europe/Vilnius`
    case europeVilnius
    /// `Europe/Volgograd`
    case europeVolgograd
    /// `Europe/Warsaw`
    case europeWarsaw
    /// `Europe/Zagreb`
    case europeZagreb
    /// `Europe/Zurich`
    case europeZurich

    // MARK: Indian

    /// `Indian/Antananarivo`
    case indianAntananarivo
    /// `Indian/Chagos`
    case indianChagos
    /// `Indian/Christmas`
    case indianChristmas
    /// `Indian/Cocos`
    case indianCocos
    /// `Indian/Comoro`
    case indianComoro
    /// `Indian/Kerguelen`
    case indianKerguelen
    /// `Indian/Mahe`
    case indianMahe
    /// `Indian/Maldives`
    case indianMaldives
    /// `Indian/Mauritius`
    case indianMauritius
    /// `Indian/Mayotte`
    case indianMayotte
    /// `Indian/Reunion`
    case indianReunion

    // MARK: Pacific

    /// `Pacific/Apia`
    case pacificApia
    /// `Pacific/Auckland`
    case pacificAuckland
    /// `Pacific/Bougainville`
    case pacificBougainville
    /// `Pacific/Chatham`
    case pacificChatham
    /// `Pacific/Chuuk`
    case pacificChuuk
    /// `Pacific/Easter`
    case pacificEaster
    /// `Pacific/Efate`
    case pacificEfate
    /// `Pacific/Fakaofo`
    case pacificFakaofo
    /// `Pacific/Fiji`
    case pacificFiji
    /// `Pacific/Funafuti`
    case pacificFunafuti
    /// `Pacific/Galapagos`
    case pacificGalapagos
    /// `Pacific/Gambier`
    case pacificGambier
    /// `Pacific/Guadalcanal`
    case pacificGuadalcanal
    /// `Pacific/Guam`
    case pacificGuam
    /// `Pacific/Honolulu`
    case pacificHonolulu
    /// `Pacific/Kanton`
    case pacificKanton
    /// `Pacific/Kiritimati`
    case pacificKiritimati
    /// `Pacific/Kosrae`
    case pacificKosrae
    /// `Pacific/Kwajalein`
    case pacificKwajalein
    /// `Pacific/Majuro`
    case pacificMajuro
    /// `Pacific/Marquesas`
    case pacificMarquesas
    /// `Pacific/Midway`
    case pacificMidway
    /// `Pacific/Nauru`
    case pacificNauru
    /// `Pacific/Niue`
    case pacificNiue
    /// `Pacific/Norfolk`
    case pacificNorfolk
    /// `Pacific/Noumea`
    case pacificNoumea
    /// `Pacific/Pago_Pago`
    case pacificPagoPago
    /// `Pacific/Palau`
    case pacificPalau
    /// `Pacific/Pitcairn`
    case pacificPitcairn
    /// `Pacific/Pohnpei`
    case pacificPohnpei
    /// `Pacific/Port_Moresby`
    case pacificPortMoresby
    /// `Pacific/Rarotonga`
    case pacificRarotonga
    /// `Pacific/Saipan`
    case pacificSaipan
    /// `Pacific/Tahiti`
    case pacificTahiti
    /// `Pacific/Tarawa`
    case pacificTarawa
    /// `Pacific/Tongatapu`
    case pacificTongatapu
    /// `Pacific/Wake`
    case pacificWake
    /// `Pacific/Wallis`
    case pacificWallis

    // MARK: Deprecated aliases

    /// `America/Godthab`, a legacy name for `America/Nuuk`.
    @available(*, deprecated, renamed: "americaNuuk")
    public static let americaGodthab: BotKitTimeZone = .americaNuuk
    /// `America/Montreal`, a legacy name for `America/Toronto`.
    @available(*, deprecated, renamed: "americaToronto")
    public static let americaMontreal: BotKitTimeZone = .americaToronto
    /// `America/Nipigon`, a legacy name for `America/Toronto`.
    @available(*, deprecated, renamed: "americaToronto")
    public static let americaNipigon: BotKitTimeZone = .americaToronto
    /// `America/Pangnirtung`, a legacy name for `America/Iqaluit`.
    @available(*, deprecated, renamed: "americaIqaluit")
    public static let americaPangnirtung: BotKitTimeZone = .americaIqaluit
    /// `America/Rainy_River`, a legacy name for `America/Winnipeg`.
    @available(*, deprecated, renamed: "americaWinnipeg")
    public static let americaRainyRiver: BotKitTimeZone = .americaWinnipeg
    /// `America/Santa_Isabel`, a legacy name for `America/Tijuana`.
    @available(*, deprecated, renamed: "americaTijuana")
    public static let americaSantaIsabel: BotKitTimeZone = .americaTijuana
    /// `America/Shiprock`, a legacy name for `America/Denver`.
    @available(*, deprecated, renamed: "americaDenver")
    public static let americaShiprock: BotKitTimeZone = .americaDenver
    /// `America/Thunder_Bay`, a legacy name for `America/Toronto`.
    @available(*, deprecated, renamed: "americaToronto")
    public static let americaThunderBay: BotKitTimeZone = .americaToronto
    /// `America/Yellowknife`, a legacy name for `America/Edmonton`.
    @available(*, deprecated, renamed: "americaEdmonton")
    public static let americaYellowknife: BotKitTimeZone = .americaEdmonton
    /// `Antarctica/South_Pole`, a legacy name for `Antarctica/McMurdo`.
    @available(*, deprecated, renamed: "antarcticaMcMurdo")
    public static let antarcticaSouthPole: BotKitTimeZone = .antarcticaMcMurdo
    /// `Asia/Calcutta`, a legacy name for `Asia/Kolkata`.
    @available(*, deprecated, renamed: "asiaKolkata")
    public static let asiaCalcutta: BotKitTimeZone = .asiaKolkata
    /// `Asia/Choibalsan`, a legacy name for `Asia/Ulaanbaatar`.
    @available(*, deprecated, renamed: "asiaUlaanbaatar")
    public static let asiaChoibalsan: BotKitTimeZone = .asiaUlaanbaatar
    /// `Asia/Chongqing`, a legacy name for `Asia/Shanghai`.
    @available(*, deprecated, renamed: "asiaShanghai")
    public static let asiaChongqing: BotKitTimeZone = .asiaShanghai
    /// `Asia/Harbin`, a legacy name for `Asia/Shanghai`.
    @available(*, deprecated, renamed: "asiaShanghai")
    public static let asiaHarbin: BotKitTimeZone = .asiaShanghai
    /// `Asia/Kashgar`, a legacy name for `Asia/Urumqi`.
    @available(*, deprecated, renamed: "asiaUrumqi")
    public static let asiaKashgar: BotKitTimeZone = .asiaUrumqi
    /// `Asia/Katmandu`, a legacy name for `Asia/Kathmandu`.
    @available(*, deprecated, renamed: "asiaKathmandu")
    public static let asiaKatmandu: BotKitTimeZone = .asiaKathmandu
    /// `Asia/Rangoon`, a legacy name for `Asia/Yangon`.
    @available(*, deprecated, renamed: "asiaYangon")
    public static let asiaRangoon: BotKitTimeZone = .asiaYangon
    /// `Australia/Currie`, a legacy name for `Australia/Hobart`.
    @available(*, deprecated, renamed: "australiaHobart")
    public static let australiaCurrie: BotKitTimeZone = .australiaHobart
    /// `Europe/Kiev`, a legacy name for `Europe/Kyiv`.
    @available(*, deprecated, renamed: "europeKyiv")
    public static let europeKiev: BotKitTimeZone = .europeKyiv
    /// `Europe/Uzhgorod`, a legacy name for `Europe/Kyiv`.
    @available(*, deprecated, renamed: "europeKyiv")
    public static let europeUzhgorod: BotKitTimeZone = .europeKyiv
    /// `Europe/Zaporozhye`, a legacy name for `Europe/Kyiv`.
    @available(*, deprecated, renamed: "europeKyiv")
    public static let europeZaporozhye: BotKitTimeZone = .europeKyiv
    /// `Pacific/Enderbury`, a legacy name for `Pacific/Kanton`.
    @available(*, deprecated, renamed: "pacificKanton")
    public static let pacificEnderbury: BotKitTimeZone = .pacificKanton
    /// `Pacific/Johnston`, a legacy name for `Pacific/Honolulu`.
    @available(*, deprecated, renamed: "pacificHonolulu")
    public static let pacificJohnston: BotKitTimeZone = .pacificHonolulu
    /// `Pacific/Ponape`, a legacy name for `Pacific/Pohnpei`.
    @available(*, deprecated, renamed: "pacificPohnpei")
    public static let pacificPonape: BotKitTimeZone = .pacificPohnpei
    /// `Pacific/Truk`, a legacy name for `Pacific/Chuuk`.
    @available(*, deprecated, renamed: "pacificChuuk")
    public static let pacificTruk: BotKitTimeZone = .pacificChuuk

    /// Every named case, `.utc` first, then alphabetically by identifier.
    /// ``custom(_:)`` and the deprecated aliases are not included.
    public static let allNamed: [BotKitTimeZone] = [
        .utc,
        .africaAbidjan,
        .africaAccra,
        .africaAddisAbaba,
        .africaAlgiers,
        .africaAsmara,
        .africaBamako,
        .africaBangui,
        .africaBanjul,
        .africaBissau,
        .africaBlantyre,
        .africaBrazzaville,
        .africaBujumbura,
        .africaCairo,
        .africaCasablanca,
        .africaCeuta,
        .africaConakry,
        .africaDakar,
        .africaDarEsSalaam,
        .africaDjibouti,
        .africaDouala,
        .africaElAaiun,
        .africaFreetown,
        .africaGaborone,
        .africaHarare,
        .africaJohannesburg,
        .africaJuba,
        .africaKampala,
        .africaKhartoum,
        .africaKigali,
        .africaKinshasa,
        .africaLagos,
        .africaLibreville,
        .africaLome,
        .africaLuanda,
        .africaLubumbashi,
        .africaLusaka,
        .africaMalabo,
        .africaMaputo,
        .africaMaseru,
        .africaMbabane,
        .africaMogadishu,
        .africaMonrovia,
        .africaNairobi,
        .africaNdjamena,
        .africaNiamey,
        .africaNouakchott,
        .africaOuagadougou,
        .africaPortoNovo,
        .africaSaoTome,
        .africaTripoli,
        .africaTunis,
        .africaWindhoek,
        .americaAdak,
        .americaAnchorage,
        .americaAnguilla,
        .americaAntigua,
        .americaAraguaina,
        .americaArgentinaBuenosAires,
        .americaArgentinaCatamarca,
        .americaArgentinaCordoba,
        .americaArgentinaJujuy,
        .americaArgentinaLaRioja,
        .americaArgentinaMendoza,
        .americaArgentinaRioGallegos,
        .americaArgentinaSalta,
        .americaArgentinaSanJuan,
        .americaArgentinaSanLuis,
        .americaArgentinaTucuman,
        .americaArgentinaUshuaia,
        .americaAruba,
        .americaAsuncion,
        .americaAtikokan,
        .americaBahia,
        .americaBahiaBanderas,
        .americaBarbados,
        .americaBelem,
        .americaBelize,
        .americaBlancSablon,
        .americaBoaVista,
        .americaBogota,
        .americaBoise,
        .americaCambridgeBay,
        .americaCampoGrande,
        .americaCancun,
        .americaCaracas,
        .americaCayenne,
        .americaCayman,
        .americaChicago,
        .americaChihuahua,
        .americaCiudadJuarez,
        .americaCostaRica,
        .americaCoyhaique,
        .americaCreston,
        .americaCuiaba,
        .americaCuracao,
        .americaDanmarkshavn,
        .americaDawson,
        .americaDawsonCreek,
        .americaDenver,
        .americaDetroit,
        .americaDominica,
        .americaEdmonton,
        .americaEirunepe,
        .americaElSalvador,
        .americaFortNelson,
        .americaFortaleza,
        .americaGlaceBay,
        .americaGooseBay,
        .americaGrandTurk,
        .americaGrenada,
        .americaGuadeloupe,
        .americaGuatemala,
        .americaGuayaquil,
        .americaGuyana,
        .americaHalifax,
        .americaHavana,
        .americaHermosillo,
        .americaIndianaIndianapolis,
        .americaIndianaKnox,
        .americaIndianaMarengo,
        .americaIndianaPetersburg,
        .americaIndianaTellCity,
        .americaIndianaVevay,
        .americaIndianaVincennes,
        .americaIndianaWinamac,
        .americaInuvik,
        .americaIqaluit,
        .americaJamaica,
        .americaJuneau,
        .americaKentuckyLouisville,
        .americaKentuckyMonticello,
        .americaKralendijk,
        .americaLaPaz,
        .americaLima,
        .americaLosAngeles,
        .americaLowerPrinces,
        .americaMaceio,
        .americaManagua,
        .americaManaus,
        .americaMarigot,
        .americaMartinique,
        .americaMatamoros,
        .americaMazatlan,
        .americaMenominee,
        .americaMerida,
        .americaMetlakatla,
        .americaMexicoCity,
        .americaMiquelon,
        .americaMoncton,
        .americaMonterrey,
        .americaMontevideo,
        .americaMontserrat,
        .americaNassau,
        .americaNewYork,
        .americaNome,
        .americaNoronha,
        .americaNorthDakotaBeulah,
        .americaNorthDakotaCenter,
        .americaNorthDakotaNewSalem,
        .americaNuuk,
        .americaOjinaga,
        .americaPanama,
        .americaParamaribo,
        .americaPhoenix,
        .americaPortAuPrince,
        .americaPortOfSpain,
        .americaPortoVelho,
        .americaPuertoRico,
        .americaPuntaArenas,
        .americaRankinInlet,
        .americaRecife,
        .americaRegina,
        .americaResolute,
        .americaRioBranco,
        .americaSantarem,
        .americaSantiago,
        .americaSantoDomingo,
        .americaSaoPaulo,
        .americaScoresbysund,
        .americaSitka,
        .americaStBarthelemy,
        .americaStJohns,
        .americaStKitts,
        .americaStLucia,
        .americaStThomas,
        .americaStVincent,
        .americaSwiftCurrent,
        .americaTegucigalpa,
        .americaThule,
        .americaTijuana,
        .americaToronto,
        .americaTortola,
        .americaVancouver,
        .americaWhitehorse,
        .americaWinnipeg,
        .americaYakutat,
        .antarcticaCasey,
        .antarcticaDavis,
        .antarcticaDumontDUrville,
        .antarcticaMacquarie,
        .antarcticaMawson,
        .antarcticaMcMurdo,
        .antarcticaPalmer,
        .antarcticaRothera,
        .antarcticaSyowa,
        .antarcticaTroll,
        .antarcticaVostok,
        .arcticLongyearbyen,
        .asiaAden,
        .asiaAlmaty,
        .asiaAmman,
        .asiaAnadyr,
        .asiaAqtau,
        .asiaAqtobe,
        .asiaAshgabat,
        .asiaAtyrau,
        .asiaBaghdad,
        .asiaBahrain,
        .asiaBaku,
        .asiaBangkok,
        .asiaBarnaul,
        .asiaBeirut,
        .asiaBishkek,
        .asiaBrunei,
        .asiaChita,
        .asiaColombo,
        .asiaDamascus,
        .asiaDhaka,
        .asiaDili,
        .asiaDubai,
        .asiaDushanbe,
        .asiaFamagusta,
        .asiaGaza,
        .asiaHebron,
        .asiaHoChiMinh,
        .asiaHongKong,
        .asiaHovd,
        .asiaIrkutsk,
        .asiaJakarta,
        .asiaJayapura,
        .asiaJerusalem,
        .asiaKabul,
        .asiaKamchatka,
        .asiaKarachi,
        .asiaKathmandu,
        .asiaKhandyga,
        .asiaKolkata,
        .asiaKrasnoyarsk,
        .asiaKualaLumpur,
        .asiaKuching,
        .asiaKuwait,
        .asiaMacau,
        .asiaMagadan,
        .asiaMakassar,
        .asiaManila,
        .asiaMuscat,
        .asiaNicosia,
        .asiaNovokuznetsk,
        .asiaNovosibirsk,
        .asiaOmsk,
        .asiaOral,
        .asiaPhnomPenh,
        .asiaPontianak,
        .asiaPyongyang,
        .asiaQatar,
        .asiaQostanay,
        .asiaQyzylorda,
        .asiaRiyadh,
        .asiaSakhalin,
        .asiaSamarkand,
        .asiaSeoul,
        .asiaShanghai,
        .asiaSingapore,
        .asiaSrednekolymsk,
        .asiaTaipei,
        .asiaTashkent,
        .asiaTbilisi,
        .asiaTehran,
        .asiaThimphu,
        .asiaTokyo,
        .asiaTomsk,
        .asiaUlaanbaatar,
        .asiaUrumqi,
        .asiaUstNera,
        .asiaVientiane,
        .asiaVladivostok,
        .asiaYakutsk,
        .asiaYangon,
        .asiaYekaterinburg,
        .asiaYerevan,
        .atlanticAzores,
        .atlanticBermuda,
        .atlanticCanary,
        .atlanticCapeVerde,
        .atlanticFaroe,
        .atlanticMadeira,
        .atlanticReykjavik,
        .atlanticSouthGeorgia,
        .atlanticStHelena,
        .atlanticStanley,
        .australiaAdelaide,
        .australiaBrisbane,
        .australiaBrokenHill,
        .australiaDarwin,
        .australiaEucla,
        .australiaHobart,
        .australiaLindeman,
        .australiaLordHowe,
        .australiaMelbourne,
        .australiaPerth,
        .australiaSydney,
        .europeAmsterdam,
        .europeAndorra,
        .europeAstrakhan,
        .europeAthens,
        .europeBelgrade,
        .europeBerlin,
        .europeBratislava,
        .europeBrussels,
        .europeBucharest,
        .europeBudapest,
        .europeBusingen,
        .europeChisinau,
        .europeCopenhagen,
        .europeDublin,
        .europeGibraltar,
        .europeGuernsey,
        .europeHelsinki,
        .europeIsleOfMan,
        .europeIstanbul,
        .europeJersey,
        .europeKaliningrad,
        .europeKirov,
        .europeKyiv,
        .europeLisbon,
        .europeLjubljana,
        .europeLondon,
        .europeLuxembourg,
        .europeMadrid,
        .europeMalta,
        .europeMariehamn,
        .europeMinsk,
        .europeMonaco,
        .europeMoscow,
        .europeOslo,
        .europeParis,
        .europePodgorica,
        .europePrague,
        .europeRiga,
        .europeRome,
        .europeSamara,
        .europeSanMarino,
        .europeSarajevo,
        .europeSaratov,
        .europeSimferopol,
        .europeSkopje,
        .europeSofia,
        .europeStockholm,
        .europeTallinn,
        .europeTirane,
        .europeUlyanovsk,
        .europeVaduz,
        .europeVatican,
        .europeVienna,
        .europeVilnius,
        .europeVolgograd,
        .europeWarsaw,
        .europeZagreb,
        .europeZurich,
        .indianAntananarivo,
        .indianChagos,
        .indianChristmas,
        .indianCocos,
        .indianComoro,
        .indianKerguelen,
        .indianMahe,
        .indianMaldives,
        .indianMauritius,
        .indianMayotte,
        .indianReunion,
        .pacificApia,
        .pacificAuckland,
        .pacificBougainville,
        .pacificChatham,
        .pacificChuuk,
        .pacificEaster,
        .pacificEfate,
        .pacificFakaofo,
        .pacificFiji,
        .pacificFunafuti,
        .pacificGalapagos,
        .pacificGambier,
        .pacificGuadalcanal,
        .pacificGuam,
        .pacificHonolulu,
        .pacificKanton,
        .pacificKiritimati,
        .pacificKosrae,
        .pacificKwajalein,
        .pacificMajuro,
        .pacificMarquesas,
        .pacificMidway,
        .pacificNauru,
        .pacificNiue,
        .pacificNorfolk,
        .pacificNoumea,
        .pacificPagoPago,
        .pacificPalau,
        .pacificPitcairn,
        .pacificPohnpei,
        .pacificPortMoresby,
        .pacificRarotonga,
        .pacificSaipan,
        .pacificTahiti,
        .pacificTarawa,
        .pacificTongatapu,
        .pacificWake,
        .pacificWallis,
    ]

    /// Legacy and backward-compatible names, mapped to the case they mean.
    static let legacyIdentifiers: [String: BotKitTimeZone] = [
        "Africa/Asmera": .africaAsmara,
        "Africa/Timbuktu": .africaAbidjan,
        "America/Argentina/ComodRivadavia": .americaArgentinaCatamarca,
        "America/Atka": .americaAdak,
        "America/Buenos_Aires": .americaArgentinaBuenosAires,
        "America/Catamarca": .americaArgentinaCatamarca,
        "America/Coral_Harbour": .americaAtikokan,
        "America/Cordoba": .americaArgentinaCordoba,
        "America/Ensenada": .americaTijuana,
        "America/Fort_Wayne": .americaIndianaIndianapolis,
        "America/Godthab": .americaNuuk,
        "America/Indianapolis": .americaIndianaIndianapolis,
        "America/Jujuy": .americaArgentinaJujuy,
        "America/Knox_IN": .americaIndianaKnox,
        "America/Louisville": .americaKentuckyLouisville,
        "America/Mendoza": .americaArgentinaMendoza,
        "America/Montreal": .americaToronto,
        "America/Nipigon": .americaToronto,
        "America/Pangnirtung": .americaIqaluit,
        "America/Porto_Acre": .americaRioBranco,
        "America/Rainy_River": .americaWinnipeg,
        "America/Rosario": .americaArgentinaCordoba,
        "America/Santa_Isabel": .americaTijuana,
        "America/Shiprock": .americaDenver,
        "America/Thunder_Bay": .americaToronto,
        "America/Virgin": .americaPuertoRico,
        "America/Yellowknife": .americaEdmonton,
        "Antarctica/South_Pole": .antarcticaMcMurdo,
        "Asia/Ashkhabad": .asiaAshgabat,
        "Asia/Calcutta": .asiaKolkata,
        "Asia/Choibalsan": .asiaUlaanbaatar,
        "Asia/Chongqing": .asiaShanghai,
        "Asia/Chungking": .asiaShanghai,
        "Asia/Dacca": .asiaDhaka,
        "Asia/Harbin": .asiaShanghai,
        "Asia/Istanbul": .europeIstanbul,
        "Asia/Kashgar": .asiaUrumqi,
        "Asia/Katmandu": .asiaKathmandu,
        "Asia/Macao": .asiaMacau,
        "Asia/Rangoon": .asiaYangon,
        "Asia/Saigon": .asiaHoChiMinh,
        "Asia/Tel_Aviv": .asiaJerusalem,
        "Asia/Thimbu": .asiaThimphu,
        "Asia/Ujung_Pandang": .asiaMakassar,
        "Asia/Ulan_Bator": .asiaUlaanbaatar,
        "Atlantic/Faeroe": .atlanticFaroe,
        "Atlantic/Jan_Mayen": .arcticLongyearbyen,
        "Australia/ACT": .australiaSydney,
        "Australia/Canberra": .australiaSydney,
        "Australia/Currie": .australiaHobart,
        "Australia/LHI": .australiaLordHowe,
        "Australia/NSW": .australiaSydney,
        "Australia/North": .australiaDarwin,
        "Australia/Queensland": .australiaBrisbane,
        "Australia/South": .australiaAdelaide,
        "Australia/Tasmania": .australiaHobart,
        "Australia/Victoria": .australiaMelbourne,
        "Australia/West": .australiaPerth,
        "Australia/Yancowinna": .australiaBrokenHill,
        "Brazil/Acre": .americaRioBranco,
        "Brazil/DeNoronha": .americaNoronha,
        "Brazil/East": .americaSaoPaulo,
        "Brazil/West": .americaManaus,
        "CET": .europeBrussels,
        "CST6CDT": .americaChicago,
        "Canada/Atlantic": .americaHalifax,
        "Canada/Central": .americaWinnipeg,
        "Canada/Eastern": .americaToronto,
        "Canada/Mountain": .americaEdmonton,
        "Canada/Newfoundland": .americaStJohns,
        "Canada/Pacific": .americaVancouver,
        "Canada/Saskatchewan": .americaRegina,
        "Canada/Yukon": .americaWhitehorse,
        "Chile/Continental": .americaSantiago,
        "Chile/EasterIsland": .pacificEaster,
        "Cuba": .americaHavana,
        "EET": .europeAthens,
        "EST": .americaPanama,
        "EST5EDT": .americaNewYork,
        "Egypt": .africaCairo,
        "Eire": .europeDublin,
        "Etc/GMT": .utc,
        "Etc/GMT+0": .utc,
        "Etc/GMT-0": .utc,
        "Etc/GMT0": .utc,
        "Etc/Greenwich": .utc,
        "Etc/UCT": .utc,
        "Etc/UTC": .utc,
        "Etc/Universal": .utc,
        "Etc/Zulu": .utc,
        "Europe/Belfast": .europeLondon,
        "Europe/Kiev": .europeKyiv,
        "Europe/Nicosia": .asiaNicosia,
        "Europe/Tiraspol": .europeChisinau,
        "Europe/Uzhgorod": .europeKyiv,
        "Europe/Zaporozhye": .europeKyiv,
        "GB": .europeLondon,
        "GB-Eire": .europeLondon,
        "GMT": .utc,
        "GMT+0": .utc,
        "GMT-0": .utc,
        "GMT0": .utc,
        "Greenwich": .utc,
        "HST": .pacificHonolulu,
        "Hongkong": .asiaHongKong,
        "Iceland": .atlanticReykjavik,
        "Iran": .asiaTehran,
        "Israel": .asiaJerusalem,
        "Jamaica": .americaJamaica,
        "Japan": .asiaTokyo,
        "Kwajalein": .pacificKwajalein,
        "Libya": .africaTripoli,
        "MET": .europeBrussels,
        "MST": .americaPhoenix,
        "MST7MDT": .americaDenver,
        "Mexico/BajaNorte": .americaTijuana,
        "Mexico/BajaSur": .americaMazatlan,
        "Mexico/General": .americaMexicoCity,
        "NZ": .pacificAuckland,
        "NZ-CHAT": .pacificChatham,
        "Navajo": .americaDenver,
        "PRC": .asiaShanghai,
        "PST8PDT": .americaLosAngeles,
        "Pacific/Enderbury": .pacificKanton,
        "Pacific/Johnston": .pacificHonolulu,
        "Pacific/Ponape": .pacificPohnpei,
        "Pacific/Samoa": .pacificPagoPago,
        "Pacific/Truk": .pacificChuuk,
        "Pacific/Yap": .pacificChuuk,
        "Poland": .europeWarsaw,
        "Portugal": .europeLisbon,
        "ROC": .asiaTaipei,
        "ROK": .asiaSeoul,
        "Singapore": .asiaSingapore,
        "Turkey": .europeIstanbul,
        "UCT": .utc,
        "US/Alaska": .americaAnchorage,
        "US/Aleutian": .americaAdak,
        "US/Arizona": .americaPhoenix,
        "US/Central": .americaChicago,
        "US/East-Indiana": .americaIndianaIndianapolis,
        "US/Eastern": .americaNewYork,
        "US/Hawaii": .pacificHonolulu,
        "US/Indiana-Starke": .americaIndianaKnox,
        "US/Michigan": .americaDetroit,
        "US/Mountain": .americaDenver,
        "US/Pacific": .americaLosAngeles,
        "US/Samoa": .pacificPagoPago,
        "UTC": .utc,
        "Universal": .utc,
        "W-SU": .europeMoscow,
        "WET": .europeLisbon,
        "Zulu": .utc,
    ]

    /// The IANA identifier, for example `America/New_York`. For
    /// ``custom(_:)``, whatever Foundation calls the zone, e.g. `GMT+0100`.
    public var identifier: String {
        switch self {
        case .utc: return "UTC"
        case .custom(let timeZone): return timeZone.identifier
        case .africaAbidjan: return "Africa/Abidjan"
        case .africaAccra: return "Africa/Accra"
        case .africaAddisAbaba: return "Africa/Addis_Ababa"
        case .africaAlgiers: return "Africa/Algiers"
        case .africaAsmara: return "Africa/Asmara"
        case .africaBamako: return "Africa/Bamako"
        case .africaBangui: return "Africa/Bangui"
        case .africaBanjul: return "Africa/Banjul"
        case .africaBissau: return "Africa/Bissau"
        case .africaBlantyre: return "Africa/Blantyre"
        case .africaBrazzaville: return "Africa/Brazzaville"
        case .africaBujumbura: return "Africa/Bujumbura"
        case .africaCairo: return "Africa/Cairo"
        case .africaCasablanca: return "Africa/Casablanca"
        case .africaCeuta: return "Africa/Ceuta"
        case .africaConakry: return "Africa/Conakry"
        case .africaDakar: return "Africa/Dakar"
        case .africaDarEsSalaam: return "Africa/Dar_es_Salaam"
        case .africaDjibouti: return "Africa/Djibouti"
        case .africaDouala: return "Africa/Douala"
        case .africaElAaiun: return "Africa/El_Aaiun"
        case .africaFreetown: return "Africa/Freetown"
        case .africaGaborone: return "Africa/Gaborone"
        case .africaHarare: return "Africa/Harare"
        case .africaJohannesburg: return "Africa/Johannesburg"
        case .africaJuba: return "Africa/Juba"
        case .africaKampala: return "Africa/Kampala"
        case .africaKhartoum: return "Africa/Khartoum"
        case .africaKigali: return "Africa/Kigali"
        case .africaKinshasa: return "Africa/Kinshasa"
        case .africaLagos: return "Africa/Lagos"
        case .africaLibreville: return "Africa/Libreville"
        case .africaLome: return "Africa/Lome"
        case .africaLuanda: return "Africa/Luanda"
        case .africaLubumbashi: return "Africa/Lubumbashi"
        case .africaLusaka: return "Africa/Lusaka"
        case .africaMalabo: return "Africa/Malabo"
        case .africaMaputo: return "Africa/Maputo"
        case .africaMaseru: return "Africa/Maseru"
        case .africaMbabane: return "Africa/Mbabane"
        case .africaMogadishu: return "Africa/Mogadishu"
        case .africaMonrovia: return "Africa/Monrovia"
        case .africaNairobi: return "Africa/Nairobi"
        case .africaNdjamena: return "Africa/Ndjamena"
        case .africaNiamey: return "Africa/Niamey"
        case .africaNouakchott: return "Africa/Nouakchott"
        case .africaOuagadougou: return "Africa/Ouagadougou"
        case .africaPortoNovo: return "Africa/Porto-Novo"
        case .africaSaoTome: return "Africa/Sao_Tome"
        case .africaTripoli: return "Africa/Tripoli"
        case .africaTunis: return "Africa/Tunis"
        case .africaWindhoek: return "Africa/Windhoek"
        case .americaAdak: return "America/Adak"
        case .americaAnchorage: return "America/Anchorage"
        case .americaAnguilla: return "America/Anguilla"
        case .americaAntigua: return "America/Antigua"
        case .americaAraguaina: return "America/Araguaina"
        case .americaArgentinaBuenosAires: return "America/Argentina/Buenos_Aires"
        case .americaArgentinaCatamarca: return "America/Argentina/Catamarca"
        case .americaArgentinaCordoba: return "America/Argentina/Cordoba"
        case .americaArgentinaJujuy: return "America/Argentina/Jujuy"
        case .americaArgentinaLaRioja: return "America/Argentina/La_Rioja"
        case .americaArgentinaMendoza: return "America/Argentina/Mendoza"
        case .americaArgentinaRioGallegos: return "America/Argentina/Rio_Gallegos"
        case .americaArgentinaSalta: return "America/Argentina/Salta"
        case .americaArgentinaSanJuan: return "America/Argentina/San_Juan"
        case .americaArgentinaSanLuis: return "America/Argentina/San_Luis"
        case .americaArgentinaTucuman: return "America/Argentina/Tucuman"
        case .americaArgentinaUshuaia: return "America/Argentina/Ushuaia"
        case .americaAruba: return "America/Aruba"
        case .americaAsuncion: return "America/Asuncion"
        case .americaAtikokan: return "America/Atikokan"
        case .americaBahia: return "America/Bahia"
        case .americaBahiaBanderas: return "America/Bahia_Banderas"
        case .americaBarbados: return "America/Barbados"
        case .americaBelem: return "America/Belem"
        case .americaBelize: return "America/Belize"
        case .americaBlancSablon: return "America/Blanc-Sablon"
        case .americaBoaVista: return "America/Boa_Vista"
        case .americaBogota: return "America/Bogota"
        case .americaBoise: return "America/Boise"
        case .americaCambridgeBay: return "America/Cambridge_Bay"
        case .americaCampoGrande: return "America/Campo_Grande"
        case .americaCancun: return "America/Cancun"
        case .americaCaracas: return "America/Caracas"
        case .americaCayenne: return "America/Cayenne"
        case .americaCayman: return "America/Cayman"
        case .americaChicago: return "America/Chicago"
        case .americaChihuahua: return "America/Chihuahua"
        case .americaCiudadJuarez: return "America/Ciudad_Juarez"
        case .americaCostaRica: return "America/Costa_Rica"
        case .americaCoyhaique: return "America/Coyhaique"
        case .americaCreston: return "America/Creston"
        case .americaCuiaba: return "America/Cuiaba"
        case .americaCuracao: return "America/Curacao"
        case .americaDanmarkshavn: return "America/Danmarkshavn"
        case .americaDawson: return "America/Dawson"
        case .americaDawsonCreek: return "America/Dawson_Creek"
        case .americaDenver: return "America/Denver"
        case .americaDetroit: return "America/Detroit"
        case .americaDominica: return "America/Dominica"
        case .americaEdmonton: return "America/Edmonton"
        case .americaEirunepe: return "America/Eirunepe"
        case .americaElSalvador: return "America/El_Salvador"
        case .americaFortNelson: return "America/Fort_Nelson"
        case .americaFortaleza: return "America/Fortaleza"
        case .americaGlaceBay: return "America/Glace_Bay"
        case .americaGooseBay: return "America/Goose_Bay"
        case .americaGrandTurk: return "America/Grand_Turk"
        case .americaGrenada: return "America/Grenada"
        case .americaGuadeloupe: return "America/Guadeloupe"
        case .americaGuatemala: return "America/Guatemala"
        case .americaGuayaquil: return "America/Guayaquil"
        case .americaGuyana: return "America/Guyana"
        case .americaHalifax: return "America/Halifax"
        case .americaHavana: return "America/Havana"
        case .americaHermosillo: return "America/Hermosillo"
        case .americaIndianaIndianapolis: return "America/Indiana/Indianapolis"
        case .americaIndianaKnox: return "America/Indiana/Knox"
        case .americaIndianaMarengo: return "America/Indiana/Marengo"
        case .americaIndianaPetersburg: return "America/Indiana/Petersburg"
        case .americaIndianaTellCity: return "America/Indiana/Tell_City"
        case .americaIndianaVevay: return "America/Indiana/Vevay"
        case .americaIndianaVincennes: return "America/Indiana/Vincennes"
        case .americaIndianaWinamac: return "America/Indiana/Winamac"
        case .americaInuvik: return "America/Inuvik"
        case .americaIqaluit: return "America/Iqaluit"
        case .americaJamaica: return "America/Jamaica"
        case .americaJuneau: return "America/Juneau"
        case .americaKentuckyLouisville: return "America/Kentucky/Louisville"
        case .americaKentuckyMonticello: return "America/Kentucky/Monticello"
        case .americaKralendijk: return "America/Kralendijk"
        case .americaLaPaz: return "America/La_Paz"
        case .americaLima: return "America/Lima"
        case .americaLosAngeles: return "America/Los_Angeles"
        case .americaLowerPrinces: return "America/Lower_Princes"
        case .americaMaceio: return "America/Maceio"
        case .americaManagua: return "America/Managua"
        case .americaManaus: return "America/Manaus"
        case .americaMarigot: return "America/Marigot"
        case .americaMartinique: return "America/Martinique"
        case .americaMatamoros: return "America/Matamoros"
        case .americaMazatlan: return "America/Mazatlan"
        case .americaMenominee: return "America/Menominee"
        case .americaMerida: return "America/Merida"
        case .americaMetlakatla: return "America/Metlakatla"
        case .americaMexicoCity: return "America/Mexico_City"
        case .americaMiquelon: return "America/Miquelon"
        case .americaMoncton: return "America/Moncton"
        case .americaMonterrey: return "America/Monterrey"
        case .americaMontevideo: return "America/Montevideo"
        case .americaMontserrat: return "America/Montserrat"
        case .americaNassau: return "America/Nassau"
        case .americaNewYork: return "America/New_York"
        case .americaNome: return "America/Nome"
        case .americaNoronha: return "America/Noronha"
        case .americaNorthDakotaBeulah: return "America/North_Dakota/Beulah"
        case .americaNorthDakotaCenter: return "America/North_Dakota/Center"
        case .americaNorthDakotaNewSalem: return "America/North_Dakota/New_Salem"
        case .americaNuuk: return "America/Nuuk"
        case .americaOjinaga: return "America/Ojinaga"
        case .americaPanama: return "America/Panama"
        case .americaParamaribo: return "America/Paramaribo"
        case .americaPhoenix: return "America/Phoenix"
        case .americaPortAuPrince: return "America/Port-au-Prince"
        case .americaPortOfSpain: return "America/Port_of_Spain"
        case .americaPortoVelho: return "America/Porto_Velho"
        case .americaPuertoRico: return "America/Puerto_Rico"
        case .americaPuntaArenas: return "America/Punta_Arenas"
        case .americaRankinInlet: return "America/Rankin_Inlet"
        case .americaRecife: return "America/Recife"
        case .americaRegina: return "America/Regina"
        case .americaResolute: return "America/Resolute"
        case .americaRioBranco: return "America/Rio_Branco"
        case .americaSantarem: return "America/Santarem"
        case .americaSantiago: return "America/Santiago"
        case .americaSantoDomingo: return "America/Santo_Domingo"
        case .americaSaoPaulo: return "America/Sao_Paulo"
        case .americaScoresbysund: return "America/Scoresbysund"
        case .americaSitka: return "America/Sitka"
        case .americaStBarthelemy: return "America/St_Barthelemy"
        case .americaStJohns: return "America/St_Johns"
        case .americaStKitts: return "America/St_Kitts"
        case .americaStLucia: return "America/St_Lucia"
        case .americaStThomas: return "America/St_Thomas"
        case .americaStVincent: return "America/St_Vincent"
        case .americaSwiftCurrent: return "America/Swift_Current"
        case .americaTegucigalpa: return "America/Tegucigalpa"
        case .americaThule: return "America/Thule"
        case .americaTijuana: return "America/Tijuana"
        case .americaToronto: return "America/Toronto"
        case .americaTortola: return "America/Tortola"
        case .americaVancouver: return "America/Vancouver"
        case .americaWhitehorse: return "America/Whitehorse"
        case .americaWinnipeg: return "America/Winnipeg"
        case .americaYakutat: return "America/Yakutat"
        case .antarcticaCasey: return "Antarctica/Casey"
        case .antarcticaDavis: return "Antarctica/Davis"
        case .antarcticaDumontDUrville: return "Antarctica/DumontDUrville"
        case .antarcticaMacquarie: return "Antarctica/Macquarie"
        case .antarcticaMawson: return "Antarctica/Mawson"
        case .antarcticaMcMurdo: return "Antarctica/McMurdo"
        case .antarcticaPalmer: return "Antarctica/Palmer"
        case .antarcticaRothera: return "Antarctica/Rothera"
        case .antarcticaSyowa: return "Antarctica/Syowa"
        case .antarcticaTroll: return "Antarctica/Troll"
        case .antarcticaVostok: return "Antarctica/Vostok"
        case .arcticLongyearbyen: return "Arctic/Longyearbyen"
        case .asiaAden: return "Asia/Aden"
        case .asiaAlmaty: return "Asia/Almaty"
        case .asiaAmman: return "Asia/Amman"
        case .asiaAnadyr: return "Asia/Anadyr"
        case .asiaAqtau: return "Asia/Aqtau"
        case .asiaAqtobe: return "Asia/Aqtobe"
        case .asiaAshgabat: return "Asia/Ashgabat"
        case .asiaAtyrau: return "Asia/Atyrau"
        case .asiaBaghdad: return "Asia/Baghdad"
        case .asiaBahrain: return "Asia/Bahrain"
        case .asiaBaku: return "Asia/Baku"
        case .asiaBangkok: return "Asia/Bangkok"
        case .asiaBarnaul: return "Asia/Barnaul"
        case .asiaBeirut: return "Asia/Beirut"
        case .asiaBishkek: return "Asia/Bishkek"
        case .asiaBrunei: return "Asia/Brunei"
        case .asiaChita: return "Asia/Chita"
        case .asiaColombo: return "Asia/Colombo"
        case .asiaDamascus: return "Asia/Damascus"
        case .asiaDhaka: return "Asia/Dhaka"
        case .asiaDili: return "Asia/Dili"
        case .asiaDubai: return "Asia/Dubai"
        case .asiaDushanbe: return "Asia/Dushanbe"
        case .asiaFamagusta: return "Asia/Famagusta"
        case .asiaGaza: return "Asia/Gaza"
        case .asiaHebron: return "Asia/Hebron"
        case .asiaHoChiMinh: return "Asia/Ho_Chi_Minh"
        case .asiaHongKong: return "Asia/Hong_Kong"
        case .asiaHovd: return "Asia/Hovd"
        case .asiaIrkutsk: return "Asia/Irkutsk"
        case .asiaJakarta: return "Asia/Jakarta"
        case .asiaJayapura: return "Asia/Jayapura"
        case .asiaJerusalem: return "Asia/Jerusalem"
        case .asiaKabul: return "Asia/Kabul"
        case .asiaKamchatka: return "Asia/Kamchatka"
        case .asiaKarachi: return "Asia/Karachi"
        case .asiaKathmandu: return "Asia/Kathmandu"
        case .asiaKhandyga: return "Asia/Khandyga"
        case .asiaKolkata: return "Asia/Kolkata"
        case .asiaKrasnoyarsk: return "Asia/Krasnoyarsk"
        case .asiaKualaLumpur: return "Asia/Kuala_Lumpur"
        case .asiaKuching: return "Asia/Kuching"
        case .asiaKuwait: return "Asia/Kuwait"
        case .asiaMacau: return "Asia/Macau"
        case .asiaMagadan: return "Asia/Magadan"
        case .asiaMakassar: return "Asia/Makassar"
        case .asiaManila: return "Asia/Manila"
        case .asiaMuscat: return "Asia/Muscat"
        case .asiaNicosia: return "Asia/Nicosia"
        case .asiaNovokuznetsk: return "Asia/Novokuznetsk"
        case .asiaNovosibirsk: return "Asia/Novosibirsk"
        case .asiaOmsk: return "Asia/Omsk"
        case .asiaOral: return "Asia/Oral"
        case .asiaPhnomPenh: return "Asia/Phnom_Penh"
        case .asiaPontianak: return "Asia/Pontianak"
        case .asiaPyongyang: return "Asia/Pyongyang"
        case .asiaQatar: return "Asia/Qatar"
        case .asiaQostanay: return "Asia/Qostanay"
        case .asiaQyzylorda: return "Asia/Qyzylorda"
        case .asiaRiyadh: return "Asia/Riyadh"
        case .asiaSakhalin: return "Asia/Sakhalin"
        case .asiaSamarkand: return "Asia/Samarkand"
        case .asiaSeoul: return "Asia/Seoul"
        case .asiaShanghai: return "Asia/Shanghai"
        case .asiaSingapore: return "Asia/Singapore"
        case .asiaSrednekolymsk: return "Asia/Srednekolymsk"
        case .asiaTaipei: return "Asia/Taipei"
        case .asiaTashkent: return "Asia/Tashkent"
        case .asiaTbilisi: return "Asia/Tbilisi"
        case .asiaTehran: return "Asia/Tehran"
        case .asiaThimphu: return "Asia/Thimphu"
        case .asiaTokyo: return "Asia/Tokyo"
        case .asiaTomsk: return "Asia/Tomsk"
        case .asiaUlaanbaatar: return "Asia/Ulaanbaatar"
        case .asiaUrumqi: return "Asia/Urumqi"
        case .asiaUstNera: return "Asia/Ust-Nera"
        case .asiaVientiane: return "Asia/Vientiane"
        case .asiaVladivostok: return "Asia/Vladivostok"
        case .asiaYakutsk: return "Asia/Yakutsk"
        case .asiaYangon: return "Asia/Yangon"
        case .asiaYekaterinburg: return "Asia/Yekaterinburg"
        case .asiaYerevan: return "Asia/Yerevan"
        case .atlanticAzores: return "Atlantic/Azores"
        case .atlanticBermuda: return "Atlantic/Bermuda"
        case .atlanticCanary: return "Atlantic/Canary"
        case .atlanticCapeVerde: return "Atlantic/Cape_Verde"
        case .atlanticFaroe: return "Atlantic/Faroe"
        case .atlanticMadeira: return "Atlantic/Madeira"
        case .atlanticReykjavik: return "Atlantic/Reykjavik"
        case .atlanticSouthGeorgia: return "Atlantic/South_Georgia"
        case .atlanticStHelena: return "Atlantic/St_Helena"
        case .atlanticStanley: return "Atlantic/Stanley"
        case .australiaAdelaide: return "Australia/Adelaide"
        case .australiaBrisbane: return "Australia/Brisbane"
        case .australiaBrokenHill: return "Australia/Broken_Hill"
        case .australiaDarwin: return "Australia/Darwin"
        case .australiaEucla: return "Australia/Eucla"
        case .australiaHobart: return "Australia/Hobart"
        case .australiaLindeman: return "Australia/Lindeman"
        case .australiaLordHowe: return "Australia/Lord_Howe"
        case .australiaMelbourne: return "Australia/Melbourne"
        case .australiaPerth: return "Australia/Perth"
        case .australiaSydney: return "Australia/Sydney"
        case .europeAmsterdam: return "Europe/Amsterdam"
        case .europeAndorra: return "Europe/Andorra"
        case .europeAstrakhan: return "Europe/Astrakhan"
        case .europeAthens: return "Europe/Athens"
        case .europeBelgrade: return "Europe/Belgrade"
        case .europeBerlin: return "Europe/Berlin"
        case .europeBratislava: return "Europe/Bratislava"
        case .europeBrussels: return "Europe/Brussels"
        case .europeBucharest: return "Europe/Bucharest"
        case .europeBudapest: return "Europe/Budapest"
        case .europeBusingen: return "Europe/Busingen"
        case .europeChisinau: return "Europe/Chisinau"
        case .europeCopenhagen: return "Europe/Copenhagen"
        case .europeDublin: return "Europe/Dublin"
        case .europeGibraltar: return "Europe/Gibraltar"
        case .europeGuernsey: return "Europe/Guernsey"
        case .europeHelsinki: return "Europe/Helsinki"
        case .europeIsleOfMan: return "Europe/Isle_of_Man"
        case .europeIstanbul: return "Europe/Istanbul"
        case .europeJersey: return "Europe/Jersey"
        case .europeKaliningrad: return "Europe/Kaliningrad"
        case .europeKirov: return "Europe/Kirov"
        case .europeKyiv: return "Europe/Kyiv"
        case .europeLisbon: return "Europe/Lisbon"
        case .europeLjubljana: return "Europe/Ljubljana"
        case .europeLondon: return "Europe/London"
        case .europeLuxembourg: return "Europe/Luxembourg"
        case .europeMadrid: return "Europe/Madrid"
        case .europeMalta: return "Europe/Malta"
        case .europeMariehamn: return "Europe/Mariehamn"
        case .europeMinsk: return "Europe/Minsk"
        case .europeMonaco: return "Europe/Monaco"
        case .europeMoscow: return "Europe/Moscow"
        case .europeOslo: return "Europe/Oslo"
        case .europeParis: return "Europe/Paris"
        case .europePodgorica: return "Europe/Podgorica"
        case .europePrague: return "Europe/Prague"
        case .europeRiga: return "Europe/Riga"
        case .europeRome: return "Europe/Rome"
        case .europeSamara: return "Europe/Samara"
        case .europeSanMarino: return "Europe/San_Marino"
        case .europeSarajevo: return "Europe/Sarajevo"
        case .europeSaratov: return "Europe/Saratov"
        case .europeSimferopol: return "Europe/Simferopol"
        case .europeSkopje: return "Europe/Skopje"
        case .europeSofia: return "Europe/Sofia"
        case .europeStockholm: return "Europe/Stockholm"
        case .europeTallinn: return "Europe/Tallinn"
        case .europeTirane: return "Europe/Tirane"
        case .europeUlyanovsk: return "Europe/Ulyanovsk"
        case .europeVaduz: return "Europe/Vaduz"
        case .europeVatican: return "Europe/Vatican"
        case .europeVienna: return "Europe/Vienna"
        case .europeVilnius: return "Europe/Vilnius"
        case .europeVolgograd: return "Europe/Volgograd"
        case .europeWarsaw: return "Europe/Warsaw"
        case .europeZagreb: return "Europe/Zagreb"
        case .europeZurich: return "Europe/Zurich"
        case .indianAntananarivo: return "Indian/Antananarivo"
        case .indianChagos: return "Indian/Chagos"
        case .indianChristmas: return "Indian/Christmas"
        case .indianCocos: return "Indian/Cocos"
        case .indianComoro: return "Indian/Comoro"
        case .indianKerguelen: return "Indian/Kerguelen"
        case .indianMahe: return "Indian/Mahe"
        case .indianMaldives: return "Indian/Maldives"
        case .indianMauritius: return "Indian/Mauritius"
        case .indianMayotte: return "Indian/Mayotte"
        case .indianReunion: return "Indian/Reunion"
        case .pacificApia: return "Pacific/Apia"
        case .pacificAuckland: return "Pacific/Auckland"
        case .pacificBougainville: return "Pacific/Bougainville"
        case .pacificChatham: return "Pacific/Chatham"
        case .pacificChuuk: return "Pacific/Chuuk"
        case .pacificEaster: return "Pacific/Easter"
        case .pacificEfate: return "Pacific/Efate"
        case .pacificFakaofo: return "Pacific/Fakaofo"
        case .pacificFiji: return "Pacific/Fiji"
        case .pacificFunafuti: return "Pacific/Funafuti"
        case .pacificGalapagos: return "Pacific/Galapagos"
        case .pacificGambier: return "Pacific/Gambier"
        case .pacificGuadalcanal: return "Pacific/Guadalcanal"
        case .pacificGuam: return "Pacific/Guam"
        case .pacificHonolulu: return "Pacific/Honolulu"
        case .pacificKanton: return "Pacific/Kanton"
        case .pacificKiritimati: return "Pacific/Kiritimati"
        case .pacificKosrae: return "Pacific/Kosrae"
        case .pacificKwajalein: return "Pacific/Kwajalein"
        case .pacificMajuro: return "Pacific/Majuro"
        case .pacificMarquesas: return "Pacific/Marquesas"
        case .pacificMidway: return "Pacific/Midway"
        case .pacificNauru: return "Pacific/Nauru"
        case .pacificNiue: return "Pacific/Niue"
        case .pacificNorfolk: return "Pacific/Norfolk"
        case .pacificNoumea: return "Pacific/Noumea"
        case .pacificPagoPago: return "Pacific/Pago_Pago"
        case .pacificPalau: return "Pacific/Palau"
        case .pacificPitcairn: return "Pacific/Pitcairn"
        case .pacificPohnpei: return "Pacific/Pohnpei"
        case .pacificPortMoresby: return "Pacific/Port_Moresby"
        case .pacificRarotonga: return "Pacific/Rarotonga"
        case .pacificSaipan: return "Pacific/Saipan"
        case .pacificTahiti: return "Pacific/Tahiti"
        case .pacificTarawa: return "Pacific/Tarawa"
        case .pacificTongatapu: return "Pacific/Tongatapu"
        case .pacificWake: return "Pacific/Wake"
        case .pacificWallis: return "Pacific/Wallis"
        }
    }
}
